/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Conexion.connbd;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar_vFonseca
 */
public class addautores extends javax.swing.JInternalFrame {
DefaultTableModel model;
    /**
     * Creates new form uautores
     */
    public addautores() {
        initComponents();
        this.setLocation(100, 60);
        tbautores("");
        bloquear();
    }
    void bloquear(){
        txtnom.setEnabled(false);
        txtape.setEnabled(false);
        txtpais.setEnabled(false);
        btnguardar.setEnabled(false);
        btnmodificar.setEnabled(false);
    }
    void desbloquear(){
        txtnom.setEnabled(true);
        txtape.setEnabled(true);
        txtpais.setEnabled(true);
        //btnguardar.setEnabled(true);
        //btnmodificar.setEnabled(true);
    }
    void limpiar(){
        txtnom.setText(null);
        txtape.setText(null);
        txtpais.setText(null);
        lblcod.setText(null);
    }
    void tbautores (String valor){
          String []titulos={"Cod","Nombre(s)","Apellido(s)","Pais"};    
          String []Registros=new String[4];
          model= new DefaultTableModel(null,titulos);
          String sql="";
          if (valor.equals("")){
              sql="CALL conautores();";
          }else{
              sql="CALL biblioteca_db.autores_buscar('%"+valor+"%')";
          }
          try {
              Statement st = cn.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while(rs.next())
              {
                  Registros[0]= rs.getString("id_autor");
                  Registros[1]= rs.getString("nombre");
                  Registros[2]= rs.getString("apellido");
                  Registros[3]= rs.getString("pais");
                  model.addRow(Registros);
              }
              tbautores.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(Libros.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popautores = new javax.swing.JPopupMenu();
        popseleccionar = new javax.swing.JMenuItem();
        popeditar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbautores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        txtpais = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblcod = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        popseleccionar.setText("Seleccionar");
        popseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popseleccionarActionPerformed(evt);
            }
        });
        popautores.add(popseleccionar);

        popeditar.setText("Modificar");
        popeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popeditarActionPerformed(evt);
            }
        });
        popautores.add(popeditar);

        setBorder(null);
        setClosable(true);
        setTitle("Autores");

        tbautores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbautores.setComponentPopupMenu(popautores);
        tbautores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbautoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbautores);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Pais");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/id copia.png"))); // NOI18N

        lblcod.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search copia.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtape)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblcod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmodificar)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcod, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       // BOTON GUARDAR
        String nom,ape,pais;
        nom=txtnom.getText();
        ape=txtape.getText();
        pais=txtpais.getText();
        String sql="CALL biblioteca_db.insautores(?,?,?);";
        
        try {
        PreparedStatement pst=cn.prepareStatement(sql);
        pst.setString(1, nom);
        pst.setString(2, ape);
        pst.setString(3, pais);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Autor Guardado");
        tbautores("");
        bloquear();
        limpiar();
        } catch (SQLException ex) {
        Logger.getLogger(addautores.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        desbloquear();
        btnguardar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void tbautoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbautoresMouseClicked
        
    }//GEN-LAST:event_tbautoresMouseClicked

    private void popeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popeditarActionPerformed
        // POP-MODIFICAR
        int fila = tbautores.getSelectedRow();
        String cod="",nom="",ape="",pais="";
        
        if (fila>=0){
            cod=(tbautores.getValueAt(fila,0).toString());
            nom=(tbautores.getValueAt(fila,1).toString());
            ape=(tbautores.getValueAt(fila,2).toString());
            pais=(tbautores.getValueAt(fila,3).toString());
        }
        lblcod.setText(cod);
        txtnom.setText(nom);
        txtape.setText(ape);
        txtpais.setText(pais);
        btnmodificar.setEnabled(true);
        desbloquear();
    }//GEN-LAST:event_popeditarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
       // BOTON MODIFICAR
        String nom,ape,pais,cod;
        nom=txtnom.getText();
        ape=txtape.getText();
        pais=txtpais.getText();
        cod=lblcod.getText();
    try{
        String sql="CALL biblioteca_db.actautores(?,?,?,?);";
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, nom);
        pst.setString(2, ape);
        pst.setString(3, pais); 
        pst.setString(4, cod);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Actualizado");
        bloquear();
        tbautores("");
        limpiar();
    } catch(SQLException ex) {
        Logger.getLogger(Libros.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void popseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popseleccionarActionPerformed
        // POP-seleccionar
        int fila = tbautores.getSelectedRow();
        String id="",nom="",ape="";
        if (fila>=0){
            id=(tbautores.getValueAt(fila,0).toString());
            nom=(tbautores.getValueAt(fila,1).toString());
            ape=(tbautores.getValueAt(fila,2).toString());
        }
        Libros.txtautor.setText(nom+" "+ape);
        Libros.codautor.setText(id);
        this.setVisible(false);
    }//GEN-LAST:event_popseleccionarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
         tbautores(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcod;
    private javax.swing.JPopupMenu popautores;
    private javax.swing.JMenuItem popeditar;
    private javax.swing.JMenuItem popseleccionar;
    private javax.swing.JTable tbautores;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpais;
    // End of variables declaration//GEN-END:variables
    connbd cc= new connbd();
    Connection cn= cc.conexion();
   
}
