/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Conexion.connbd;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar_vFonseca
 */
public class aPrestamos extends javax.swing.JInternalFrame {
DefaultTableModel model;
    /**
     * Creates new form aPrestamos
     */
    public aPrestamos() {
        initComponents();
        tbpr("");
    }
    void limpiar(){
            lblidp.setText(null);
            lblcod.setText(null);
            lblnom.setText(null);
            lblidl.setText(null);
            lbltit.setText(null);
            lblfec1.setText(null);
            lblfec2.setText(null);
            fec3.setText(null);
    }
    void Calendario(){
         Calendar cal = Calendar.getInstance();
         cal.getTime();
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
         lblfec2.setText(sdf.format(cal.getTime()));
    }
    void tbpr(String valor){
                String []titulos={"Cod_Prestamo","Id","Usuario","Cod_lib","Titulo","fecha prestamo","fecha compromiso","Fecha devolucion","Status","Sistema"};
                String []Registros= new String[10];
                model = new DefaultTableModel(null,titulos);
                String sql="";
                if (valor.equals("")){
                sql = "CALL pr_user();";
                  }else{
                sql="CALL con_prs2('%"+valor+"%');";
                }
            try{
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                          while(rs.next())
                          {
                              Registros[0]= rs.getString("id_p");
                              Registros[1]= rs.getString("cod_usuario");
                              Registros[2]= rs.getString("nom");
                              Registros[3]= rs.getString("cod_libro");
                              Registros[4]= rs.getString("titulo");
                              Registros[5]= rs.getString("fecha_salida");
                              Registros[6]= rs.getString("fecha_maxima");
                              Registros[7]= rs.getString("fecha_devolucion");
                              Registros[8]= rs.getString("Status");
                              Registros[9]= rs.getString("status_sistema");
                              model.addRow(Registros);
                          }
                            tbpr.setModel(model);
                            } catch (SQLException ex) {
                            Logger.getLogger(aPrestamos.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        popseleccionar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpr = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblidp = new javax.swing.JLabel();
        lblidl = new javax.swing.JLabel();
        lblcod = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        lbltit = new javax.swing.JLabel();
        lblfec1 = new javax.swing.JLabel();
        lblfec2 = new javax.swing.JLabel();
        btnrecibir = new javax.swing.JButton();
        fec3 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();

        popseleccionar.setText("Seleccionar");
        popseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popseleccionarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popseleccionar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Prestamos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Prestamos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        tbpr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbpr.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbpr);

        txtbuscar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search copia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtbuscar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        lblidp.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblidp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblidp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 8))); // NOI18N

        lblidl.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblidl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID LIBRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 8))); // NOI18N

        lblcod.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblcod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 8))); // NOI18N

        lblnom.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblnom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TITULO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 8))); // NOI18N

        lbltit.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbltit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE(S)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 8))); // NOI18N

        lblfec1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblfec1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA PRESTAMO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 8))); // NOI18N

        lblfec2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblfec2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DEVOLUCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 8))); // NOI18N

        btnrecibir.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnrecibir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok2.png"))); // NOI18N
        btnrecibir.setText("Recibir");
        btnrecibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecibirActionPerformed(evt);
            }
        });

        fec3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        fec3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA COMPROMISO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 8))); // NOI18N

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete copia.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidl, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lblcod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbltit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fec3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btncancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnrecibir))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblnom, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblfec1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblfec2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblidp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblfec1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblidl, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(lblnom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblfec2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbltit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fec3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnrecibir)
                        .addComponent(btncancelar)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed

    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed

    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        tbpr(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void popseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popseleccionarActionPerformed
        int fila = tbpr.getSelectedRow();
        if (fila>=0){
            lblidp.setText(tbpr.getValueAt(fila,0).toString());
            lblcod.setText(tbpr.getValueAt(fila,1).toString());
            lbltit.setText(tbpr.getValueAt(fila,2).toString());
            lblidl.setText(tbpr.getValueAt(fila,3).toString());
            lblnom.setText(tbpr.getValueAt(fila,4).toString());
            lblfec1.setText(tbpr.getValueAt(fila,5).toString());
            fec3.setText(tbpr.getValueAt(fila,6).toString());
            Calendario();
        }
    }//GEN-LAST:event_popseleccionarActionPerformed

    private void btnrecibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecibirActionPerformed
        // BOTON RECIBIR
        String idpr,fec1,fec2,dat3,idl,codu,st;
        idpr=lblidp.getText();
        fec1=lblfec1.getText();
        dat3=fec3.getText();
        fec2=lblfec2.getText();
        st="C";
        idl=lblidl.getText();
        codu=lblcod.getText();
     
        String sql="CALL up_pr(?,?,?,?,?,?,?);";
        try {
                PreparedStatement env = cn.prepareStatement(sql);//CREAMOS EL METODO QUE EJECUTARA AL PROCEDIMIENTO ALMACENADO
                env.setString(1, idpr);
                env.setString(2, fec1);
                env.setString(3, dat3);
                env.setString(4, fec2);
                env.setString(5, st);
                env.setString(6, idl);
                env.setString(7, codu);
                env.executeUpdate();
                limpiar();
                tbpr("");
                JOptionPane.showMessageDialog(null, "Elemento actualizado");
                } catch (SQLException ex) {
            Logger.getLogger(aPrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnrecibirActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // BOTON CANCELAR
        limpiar();
    }//GEN-LAST:event_btncancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnrecibir;
    private javax.swing.JLabel fec3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcod;
    private javax.swing.JLabel lblfec1;
    private javax.swing.JLabel lblfec2;
    private javax.swing.JLabel lblidl;
    private javax.swing.JLabel lblidp;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lbltit;
    private javax.swing.JMenuItem popseleccionar;
    private javax.swing.JTable tbpr;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
        connbd cc= new connbd();
        Connection cn= cc.conexion();
}
