/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Conexion.connbd;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar_vFonseca
 */
public class Clientes extends javax.swing.JInternalFrame {
         DefaultTableModel model;
    /**
     * Creates new form AltaClientes
     */
    public Clientes() {
        initComponents();
        this.setLocation(5, 10);//POSICION PARA INICIAR LA PANTALLA 
        mostrard("");
        bloquear();//LLAMAR METODO
        tbclientes.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }
    void bloquear(){//CREACION DEL METODO PARA BLOQUEAR EL FORMULARIO
        txtnom.setEnabled(false);
        txtape.setEnabled(false);
        comsex.setEnabled(false);
        txtdom.setEnabled(false);
        txtcd.setEnabled(false);
        txttel.setEnabled(false);
        txtmail.setEnabled(false);
        txtcp.setEnabled(false);
        jpwd.setEnabled(false);
        jDate.setEnabled(false);
        comtipo.setEnabled(false);
        btnguardar.setEnabled(false);
        btnmodificar.setEnabled(false);
        btncancelar.setEnabled(false);
    }
    void desbloquear(){//CREACION DEL METODO PARA DESBLOQUEAR EL FORMULARIO
        txtnom.setEnabled(true);
        txtape.setEnabled(true);
        comsex.setEnabled(true);
        txtdom.setEnabled(true);
        txtcd.setEnabled(true);
        txttel.setEnabled(true);
        txtmail.setEnabled(true);
        txtcp.setEnabled(true);
        jpwd.setEnabled(true);
        jDate.setEnabled(true);
        comtipo.setEnabled(true);
        btnguardar.setEnabled(true);
        btncancelar.setEnabled(true);
    }
    void limpiar(){//CREACION DEL METODO PARA LIMPIAR EL FORMULARIO
        txtnom.setText(null);
        txtape.setText(null);
        comsex.setSelectedItem(null);
        txtdom.setText(null);
        txtcd.setText(null);
        txttel.setText(null);
        txtmail.setText(null);
        txtcp.setText(null);
        jpwd.setText(null);
        jDate.setDate(null);
        comtipo.setSelectedItem(null);
        lbid.setText(null);
    }
    void mostrard (String valor){
          String []titulos={"Codigo","Nombres","Apellidos","Sexo","Domicilio","Ciudad","Telefono","Correo","CP","Fecha de Nacimiento","Tipo","Pass"};    
          String []Registros=new String[12];
          model= new DefaultTableModel(null,titulos);
          String sql="";
          if (valor.equals("")){
              sql="CALL con_clientes;";
          }else{
              sql="CALL con_clientes2('%"+valor+"%');";
          }
            try {
              Statement st = cn.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while(rs.next())
              {
                  Registros[0]= rs.getString("cod_usuario");
                  Registros[1]= rs.getString("nombre");
                  Registros[2]= rs.getString("apellido");
                  Registros[3]= rs.getString("sexo");
                  Registros[4]= rs.getString("domicilio");
                  Registros[5]= rs.getString("ciudad");
                  Registros[6]= rs.getString("telefono");
                  Registros[7]= rs.getString("correo");
                  Registros[8]= rs.getString("cp");
                  Registros[9]= rs.getString("fecha_nacimiento");
                  Registros[10]= rs.getString("tipo");
                  Registros[11]= rs.getString("contra");
                  model.addRow(Registros);
              }
              tbclientes.setModel(model);
               
                } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
                }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jmodificar = new javax.swing.JMenuItem();
        jeliminar = new javax.swing.JMenuItem();
        datoscli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        comsex = new javax.swing.JComboBox();
        txtdom = new javax.swing.JTextField();
        txtcd = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtcp = new javax.swing.JTextField();
        comtipo = new javax.swing.JComboBox();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jpwd = new javax.swing.JPasswordField();
        lbid = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbclientes = new javax.swing.JTable();
        btnsalir = new javax.swing.JButton();
        lbbuscar = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jmodificar.setText("Modificar");
        jmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jmodificar);

        jeliminar.setText("Eliminar");
        jeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jeliminar);

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alta de Usuarios");

        datoscli.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Nombre(s)");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setText("Apellido(s)");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Sexo");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setText("Domicilio");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel5.setText("Ciudad");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setText("Telefono");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setText("Nick");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("C.P.");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setText("Fecha de Nacimiento");

        jLabel10.setText("Tipo");

        comsex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "H", "M" }));

        comtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", "Administrador" }));

        jDate.setDateFormatString("yyyy-MM-dd");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel11.setText("Contraseña");

        lbid.setBackground(new java.awt.Color(204, 204, 204));
        lbid.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        lbid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbid.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel12.setText("ID");

        javax.swing.GroupLayout datoscliLayout = new javax.swing.GroupLayout(datoscli);
        datoscli.setLayout(datoscliLayout);
        datoscliLayout.setHorizontalGroup(
            datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datoscliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datoscliLayout.createSequentialGroup()
                        .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datoscliLayout.createSequentialGroup()
                                .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(datoscliLayout.createSequentialGroup()
                                        .addComponent(comsex, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addGap(10, 10, 10)
                                        .addComponent(comtipo, 0, 120, Short.MAX_VALUE))
                                    .addGroup(datoscliLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txttel))
                                    .addComponent(txtdom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29))
                            .addGroup(datoscliLayout.createSequentialGroup()
                                .addComponent(txtcd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(datoscliLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(datoscliLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbid, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        datoscliLayout.setVerticalGroup(
            datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datoscliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datoscliLayout.createSequentialGroup()
                        .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(comsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(txtcp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(comtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9))
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnnuevo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newuser.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save copia.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit_user copia.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close copia.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });

        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbclientes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane3.setViewportView(tbclientes);

        btnsalir.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close_2.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        lbbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search copia.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbbuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(datoscli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnsalir)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(datoscli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        datoscli.getAccessibleContext().setAccessibleName("Detalles Clientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        //Boton Nuevo
        desbloquear();//ESTE BOTON MANDA LLAMAR AL METODO
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // Boton Guardar 
        String d,m,a;//SE DECLARAN LAS VARIABLES DE DIA, MES Y AÑO PARA LA FECHA
                d=Integer.toString(jDate.getCalendar().get(Calendar.DAY_OF_MONTH));//OBTENEMOS EL DIA DEL JDATE
                m=Integer.toString(jDate.getCalendar().get(Calendar.MONTH));//OBTENEMOS EL MES DEL JDATE
                a=Integer.toString(jDate.getCalendar().get(Calendar.YEAR));//OBTENEMOS EL AÑO DEL JDATE
        String nom,ape,sex,dom,cd,tel,mail,cp,fec_nac,tipo,pwd;//SE DECLARAN LAS VARIABLES QUE RECINIRAN LOS DATOS DEL FORMULARIO
                nom=txtnom.getText();
                ape=txtape.getText();
                sex=comsex.getSelectedItem().toString();
                dom=txtdom.getText();
                cd=txtcd.getText();
                tel=txttel.getText();
                mail=txtmail.getText();
                cp=txtcp.getText();
                fec_nac=(a+"-"+m+"-"+d);
                tipo=comtipo.getSelectedItem().toString();
                pwd=jpwd.getText();
            
            String sql="call biblioteca_db.altacli(?,?,?,?,?,?,?,?,?,?,?);";//LLAMANDO PROCEDIMIENTO ALMACENADO
       if(nom.isEmpty()||ape.isEmpty()||dom.isEmpty()||cd.isEmpty()||tel.isEmpty()||mail.isEmpty()||
            cp.isEmpty()||fec_nac.isEmpty()||pwd.isEmpty()){
            JOptionPane.showMessageDialog(null, "Falta campos por llenar, favor de verificar");
        }else{
        try {
                PreparedStatement env = cn.prepareStatement(sql);//CREAMOS EL METODO QUE EJECUTARA AL PROCEDIMIENTO ALMACENADO
                env.setString(1, nom);
                env.setString(2, ape);
                env.setString(3, sex);
                env.setString(4, dom);
                env.setString(5, cd);
                env.setString(6, tel);
                env.setString(7, mail);
                env.setString(8, cp);
                env.setString(9, fec_nac);
                env.setString(10, tipo);
                env.setString(11, pwd);
                env.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
                limpiar();
                bloquear();
                mostrard("");
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
        mostrard(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void jmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodificarActionPerformed
        // TODO add your handling code here:
        btnmodificar.setEnabled(true);
        desbloquear();
        btnguardar.setEnabled(false);
        btnnuevo.setEnabled(false);
        int fila = tbclientes.getSelectedRow();
        if (fila>=0){
            lbid.setText(tbclientes.getValueAt(fila,0).toString());
            txtnom.setText(tbclientes.getValueAt(fila,1).toString());
            txtape.setText(tbclientes.getValueAt(fila,2).toString());
            comsex.setSelectedItem(tbclientes.getValueAt(fila, 3).toString());
            txtdom.setText(tbclientes.getValueAt(fila,4).toString());
            txtcd.setText(tbclientes.getValueAt(fila,5).toString());
            txttel.setText(tbclientes.getValueAt(fila,6).toString());
            txtmail.setText(tbclientes.getValueAt(fila,7).toString());
            txtcp.setText(tbclientes.getValueAt(fila,8).toString());
            jDate.setDate(Date.valueOf(tbclientes.getValueAt(fila,9).toString()));
            comtipo.setSelectedItem(tbclientes.getValueAt(fila, 10).toString());
            jpwd.setText(tbclientes.getValueAt(fila,11).toString());
        }else{
                JOptionPane.showMessageDialog(null,"No selecciono fila");   
        }
    }//GEN-LAST:event_jmodificarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        String sql="CALL actclient(?,?,?,?,?,?,?,?,?,?,?,?)";
        String d,m,a;//SE DECLARAN LAS VARIABLES DE DIA, MES Y AÑO PARA LA FECHA
            d=Integer.toString(jDate.getCalendar().get(Calendar.DAY_OF_MONTH));//OBTENEMOS EL DIA DEL JDATE
            m=Integer.toString(jDate.getCalendar().get(Calendar.MONTH));//OBTENEMOS EL MES DEL JDATE
            a=Integer.toString(jDate.getCalendar().get(Calendar.YEAR));//OBTENEMOS EL AÑO DEL JDATE
        String fecha;
        fecha=(a+"-"+m+"-"+d);
            try {
                 PreparedStatement pst = cn.prepareStatement(sql);
                 pst.setString(1, lbid.getText());
                 pst.setString(2, txtnom.getText());
                 pst.setString(3, txtape.getText());
                 pst.setString(4, (String) comsex.getSelectedItem());
                 pst.setString(5, txtdom.getText());
                 pst.setString(6, txtcd.getText());
                 pst.setString(7, txttel.getText());
                 pst.setString(8, txtmail.getText());
                 pst.setString(9, txtcp.getText());
                 pst.setString(10, fecha);
                 pst.setString(11, (String) comtipo.getSelectedItem());
                 pst.setString(12, jpwd.getText());
                 pst.executeUpdate();
                 limpiar();
                 mostrard("");
                 bloquear();
             } catch (SQLException ex) {
                 Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void jeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeliminarActionPerformed
        // TODO add your handling code here:
        int fila = tbclientes.getSelectedRow();
        String cod="";
        cod=tbclientes.getValueAt(fila, 0).toString();
        String sql="CALL biblioteca_db.delclient("+cod+");";
        PreparedStatement pst;
        try {
            pst = cn.prepareStatement(sql);
            pst.executeUpdate();
            mostrard("");
            setEnabled(true);
        } catch (SQLException e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_jeliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiar();
        bloquear();
        setEnabled(true);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox comsex;
    private javax.swing.JComboBox comtipo;
    private javax.swing.JPanel datoscli;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenuItem jeliminar;
    private javax.swing.JMenuItem jmodificar;
    private javax.swing.JPasswordField jpwd;
    private javax.swing.JLabel lbbuscar;
    private javax.swing.JLabel lbid;
    private javax.swing.JTable tbclientes;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcd;
    private javax.swing.JTextField txtcp;
    private javax.swing.JTextField txtdom;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
    connbd cc= new connbd();
    Connection cn= cc.conexion();
}
