/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;

import Conexion.ImagenFondo;
import Conexion.connbd;
import Pantallas.pantalla_ingreso;
import Pantallas.reloj;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cesar_vFonseca
 */
public class userMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public userMenu() {
        initComponents();
        uescritorio.setBorder(new ImagenFondo());
        //this.setExtendedState(userMenu.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }
    void Calendario(){
         Calendar cal = Calendar.getInstance();
         cal.getTime();
         SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyy");
         lbfecha.setText(sdf.format(cal.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uescritorio = new javax.swing.JDesktopPane();
        connuser = new javax.swing.JLabel();
        lbcon = new javax.swing.JLabel();
        uhora = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jclose = new javax.swing.JMenuItem();
        jlogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mpr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        connuser.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        connuser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        connuser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbcon.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbcon.setText("Conectado como:");

        uhora.setFont(new java.awt.Font("Century Gothic", 1, 35)); // NOI18N
        uhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uhora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        uhora.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                uhoraAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbfecha.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lbfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbfecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbfecha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbfechaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout uescritorioLayout = new javax.swing.GroupLayout(uescritorio);
        uescritorio.setLayout(uescritorioLayout);
        uescritorioLayout.setHorizontalGroup(
            uescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uescritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(uescritorioLayout.createSequentialGroup()
                        .addComponent(lbcon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connuser, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(lbfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(718, Short.MAX_VALUE))
        );
        uescritorioLayout.setVerticalGroup(
            uescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uescritorioLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addGroup(uescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(connuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uhora, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        uescritorio.setLayer(connuser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        uescritorio.setLayer(lbcon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        uescritorio.setLayer(uhora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        uescritorio.setLayer(lbfecha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sys_en.png"))); // NOI18N
        jMenu1.setText("Sistema");

        jclose.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signout.png"))); // NOI18N
        jclose.setText("Cerrar sesión");
        jclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcloseActionPerformed(evt);
            }
        });
        jMenu1.add(jclose);

        jlogout.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close_2.png"))); // NOI18N
        jlogout.setText("Salir");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jlogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/conj.png"))); // NOI18N
        jMenu2.setText("Consultar");

        jMenuItem3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book_2.png"))); // NOI18N
        jMenuItem3.setText("Libros");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        mpr.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/date_p copia.png"))); // NOI18N
        mpr.setText("Prestamos");
        mpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprActionPerformed(evt);
            }
        });
        jMenu2.add(mpr);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uescritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcloseActionPerformed
        pantalla_ingreso principal= new pantalla_ingreso();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jcloseActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String mail = connuser.getText();
        String cod="",nom="",ape="";
        String sql = "SELECT * FROM biblioteca_db.usuarios WHERE correo='"+mail+"';";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                cod=rs.getString("cod_usuario");
                nom=rs.getString("nombre");
                ape=rs.getString("apellido");
            }
        ulibros lib = new ulibros();
        uescritorio.add(lib);
        lib.show();
        ulibros.lblid.setText(cod);
        ulibros.usrlbl.setText(nom+" "+ape);
        } catch (SQLException ex) {
            Logger.getLogger(pantalla_ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprActionPerformed
        // Mostrar tabla prestamos
        String mail = connuser.getText();
        String cod="",nom="",ape="",sexo="",dom="",cd="",tel="",correo="",cp="",f_n="";
        String sql = "SELECT * FROM biblioteca_db.usuarios WHERE correo='"+mail+"';";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                cod=rs.getString("cod_usuario");
                nom=rs.getString("nombre");
                ape=rs.getString("apellido");
                sexo=rs.getString("sexo");
                dom=rs.getString("domicilio");
                cd=rs.getString("ciudad");
                tel=rs.getString("telefono");
                correo=rs.getString("correo");
                cp=rs.getString("cp");
                f_n=rs.getString("fecha_nacimiento");
            }
        uprestamos upr = new uprestamos();
        uescritorio.add(upr);
        upr.show();
        uprestamos.lblid.setText(cod);
        uprestamos.btnid.setText(cod);
        uprestamos.lblnom.setText("Nombre(s): "+nom+" "+ape);
        uprestamos.lbltel.setText("Telefono: "+tel);
        uprestamos.lblcorreo.setText("Correo: "+correo);
        uprestamos.lbldom.setText("Domicilio: "+dom);
        uprestamos.lblcd.setText("Ciudad: "+cd);
        uprestamos.lblcp.setText("CP: "+cp);
        uprestamos.lbldate.setText("Fecha de Nacimiento: "+f_n);
        } catch (SQLException ex) {
            Logger.getLogger(pantalla_ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mprActionPerformed

    private void uhoraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_uhoraAncestorAdded
            new ureloj();
    }//GEN-LAST:event_uhoraAncestorAdded

    private void lbfechaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbfechaAncestorAdded
        Calendario();
    }//GEN-LAST:event_lbfechaAncestorAdded
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel connuser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jclose;
    private javax.swing.JMenuItem jlogout;
    private javax.swing.JLabel lbcon;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JMenuItem mpr;
    private javax.swing.JDesktopPane uescritorio;
    public static javax.swing.JLabel uhora;
    // End of variables declaration//GEN-END:variables
    connbd cc= new connbd();
    Connection cn= cc.conexion();   
}
